version: '3.5'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: bank-account-web # Use an image built from the specified dockerfile.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:h2:mem:DB_BANK
      SPRING_H2_CONSOLE_ENABLED: "true"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service
  app-client:
    build:
      context: bank-account-web # Use an image built from the specified dockerfile.
      dockerfile: ../bank-account-web/Dockerfile
    ports:
      - "4200:4200"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: